# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Near Me' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Near Me
  pod 'Alamofire', '~> 4.9.1'
  pod 'PromiseKit', '~> 6.3.1'
  pod 'SwiftLint'
  pod 'CodableAlamofire', '~> 1.1.2'
  pod 'SwiftyBeaver', '~> 1.8.4'
  pod 'AlamofireImage'
  pod 'lottie-ios'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'Swinject', '~> 2.6.0'
  pod 'SwinjectAutoregistration', '~> 2.6.0'
  pod 'SwinjectStoryboard'
  pod 'RealmSwift'

end
